name: test

on:
  pull_request_target:
    paths: ["**.json", "**.cpp", "**.hpp", "**.h", "**.c", "**.ts"]
  pull_request:
    paths: ["**.json", "**.cpp", "**.hpp", "**.h", "**.c", "**.ts"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: denoland/setup-deno@v1

      - run: deno fmt --check
      - run: deno lint
      - run: deno test --allow-read

      - uses: reviewdog/action-suggester@v1
        if: ${{ always() }}
        with:
          tool_name: deno
